arm_group:
  kinematics_solver: xrsolve_ik_kinematics_plugin/XRSOLVE_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  position_only_ik: True
